on:
  push:
    branches: [main]

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: copy
          path: src/**
          retention-days: 1
  public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: copy
          path: public
      - run: |
          tar -cJf public.tar.xz public
      - uses: actions/upload-artifact@v3
        with:
          name: public
          path: public.tar.xz
